export default [
  { title: "Overview", path: "/" },
  { title: "Getting Started", path: "/getting-started" },
  [
    "Components",
    { title: "Activity Indicator", path: "/components/activity-indicator" },
    { title: "App Bar", path: "/components/app-bar" },
    { title: "Avatar", path: "/components/avatar" },
    { title: "Backdrop", path: "/components/backdrop" },
    { title: "Badge", path: "/components/badge" },
    { title: "Banner", path: "/components/banner" },
    { title: "Button", path: "/components/button" },
    { title: "Chip", path: "/components/chip" },
    { title: "Dialog", path: "/components/dialog" },
    { title: "Divider", path: "/components/divider" },
    { title: "Fab", path: "/components/fab" },
    { title: "Icon Button", path: "/components/icon-button" },
    { title: "Icon", path: "/components/icon" },
    { title: "List Item", path: "/components/list-item" },
    { title: "Portal", path: "/components/portal" },
    { title: "Pressable", path: "/components/pressable" },
    { title: "Snackbar", path: "/components/snackbar" },
    { title: "Surface", path: "/components/surface" },
    { title: "Switch", path: "/components/switch" },
    { title: "Text Input", path: "/components/text-input" },
    { title: "Text", path: "/components/text" },
  ],
  [
    "Layout",
    { title: "Box", path: "/layout/box" },
    { title: "Flex", path: "/layout/flex" },
    { title: "Stack", path: "/layout/stack" },
    { title: "Wrap", path: "/layout/wrap" },
    { title: "Selector", path: "/layout/selector" },
    { title: "Spacer", path: "/layout/spacer" },
    { title: "Divider", path: "/layout/divider" },
  ],
  [
    "Hooks",
    { title: "useBoolean", path: "/hooks/use-boolean" },
    { title: "useTheme", path: "/hooks/use-theme" },
  ],
]
